import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#a3f69c",
        "error-container": "#ffdad6",
        "on-background": "#191d19",
        "secondary-fixed-dim": "#ffb77a",
        "surface-tint": "#1b6d24",
        "inverse-primary": "#88d982",
        "surface-variant": "#e0e3dd",
        "background": "#f7faf3",
        "on-tertiary-container": "#defbbd",
        tertiary: "#455c2d",
        "tertiary-fixed": "#d0ecaf",
        "on-primary-fixed": "#002204",
        "tertiary-fixed-dim": "#b4cf95",
        "tertiary-container": "#5d7543",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#6d3a00",
        "on-primary": "#ffffff",
        secondary: "#8f4e00",
        "on-tertiary": "#ffffff",
        surface: "#f7faf3",
        primary: "#0d631b",
        "on-secondary-fixed": "#2e1500",
        "on-primary-fixed-variant": "#005312",
        "on-surface-variant": "#40493d",
        "surface-container-highest": "#e0e3dd",
        error: "#ba1a1a",
        "inverse-on-surface": "#eff2eb",
        "on-error": "#ffffff",
        "secondary-container": "#ff8f00",
        "surface-bright": "#f7faf3",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#374d20",
        "on-primary-container": "#cbffc2",
        outline: "#707a6c",
        "surface-dim": "#d8dbd4",
        "on-secondary-container": "#623400",
        "surface-container-high": "#e6e9e2",
        "surface-container": "#ecefe8",
        "outline-variant": "#bfcaba",
        "primary-fixed-dim": "#88d982",
        "on-tertiary-fixed": "#0e2000",
        "secondary-fixed": "#ffdcc2",
        "primary-container": "#2e7d32",
        "on-surface": "#191d19",
        "surface-container-low": "#f2f5ee",
        "on-error-container": "#93000a",
        "inverse-surface": "#2d312d",
      },
      fontFamily: {
        headline: ["var(--font-headline)"],
        body: ["var(--font-body)"],
        label: ["var(--font-body)"],
      },
    },
  },
  plugins: [],
} satisfies Config;
